### ISSUE TITLE
Windows fail

### ISSUE THREAD

**Issue by lucasjinreal** [wkentaro/imshow#9]
imshow ./*.png

imgviz\_io\base.py", line 24, in imread
    return utils.pillow_to_numpy(PIL.Image.open(filename))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniconda\Lib\site-packages\PIL\Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: './*.png'

I have pngs under currect folder

**Comment by wkentaro** [comment]
It looks like the due to the split symbol difference b/w unix and windows. I'll check soon.

**Comment by wkentaro** [comment]
Seems Windows shell won't expand glob, so Imshow has to.
Click had the same issue: https://github.com/pallets/click/pull/1830

I'll do this, but I ran out of the screen time today.
In the meantime, can you use `imshow . --recursive`? @lucasjinreal

**Comment by wkentaro** [comment]
@lucasjinreal This is resolved via https://github.com/wkentaro/imshow/pull/11, and released with v0.2.3.
Please upgrade via `pip install -U imshow`.
